spring.application.name=Mission2

spring.mongodb.uri=mongodb://localhost:27017/hospital

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.output.ansi.enabled=always