spring.application.name=Mission2

#spring.mongodb.uri=mongodb://localhost:27017/hospital
spring.mongodb.uri=mongodb://ye:1234@139.59.227.83:27017/hospital?authSource=admin

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.output.ansi.enabled=always

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always